Release/v3.0.0
nasa/cumulus-orca pull request #108
Opened 2021-06-23 19:31 UTC by bhazuka

## Summary of Changes

Please write a sentence or two summarizing the proposed change.

Addresses [ORCA-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/ORCA-XXX)

## Changes

* Detailed list or prose of changes
* ...

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests (unit, integration, ad-hoc, or otherwise) that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [ ] CHANGELOG.md
    - [ ] Testing documentation
    - [ ] Development documentation
    - [ ] User documentation
    - [ ] (Additional here)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] Unit tests
    - [ ] Integration tests
    - [ ] Manual tests (outlined above)
- [ ] New and existing unit tests pass locally with my changes
    - [ ] Automated tests passing (if not fork)
    - [ ] Manual testing/integration testing passes (if forked)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code has passed security scanning
    - [ ] Snyk
    - [ ] git-secrets

## What is the current behavior?

(What actually happens)

## What is the expected correct/added behavior?

(What you should see instead)

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

## Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

2021-06-29 20:24 UTC, AndrewDorn requested changes

2021-06-29 20:24 UTC, AndrewDorn commented on tasks/request_files/request_files.py
> +        # If no errors add to copied_granules array for output.
I might remove the "If no errors" since that isn't really a factor beyond as much as it is for any line.

2021-06-29 20:24 UTC, AndrewDorn commented on tasks/request_files/request_files.py
> +        # If no errors add to copied_granules array for output.
Did you mean to have a try/except around process_granule?

2021-06-29 20:24 UTC, AndrewDorn commented on tasks/request_files/request_files.py
> +                        a_file["key_path"],
Does not match input.json

2021-06-29 20:24 UTC, AndrewDorn commented on tasks/request_files/request_files.py
>          # todo: This is either a lie, or the loop below should be removed.  ORCA-202
Looks like you've resolved everything having to do with ORCA-202

2021-06-30 18:36 UTC, AndrewDorn requested changes
Some more test issues. My guess is that some tests are failing/would fail for the wrong reasons.

2021-06-30 18:36 UTC, AndrewDorn commented on tasks/post_copy_request_to_queue/test/unit_tests/test_post_copy_request_to_queue.py
> +    @patch("post_copy_request_to_queue.get_metadata_sql")  # todo: Unit test this sql?
We probably want a basic happy-path test for this function now that SQLAlchemy makes checking the raw string harder.

2021-06-30 18:36 UTC, AndrewDorn commented on tasks/post_copy_request_to_queue/test/unit_tests/test_post_copy_request_to_queue.py
> +            # todo: Value incorrect here and elsewhere. As written, must match mock_execute's return value.
Looking now, I don't see any other issues where the restore_destination and mock_execute have different values.

2021-06-30 18:36 UTC, AndrewDorn commented on tasks/post_copy_request_to_queue/test/unit_tests/test_post_copy_request_to_queue.py
> +            mock_get_dbconnect_info: MagicMock,
2 mislabeled mocks. Make the same changes here as in happy-path.

2021-06-30 18:36 UTC, AndrewDorn commented on tasks/post_copy_request_to_queue/test/unit_tests/test_post_copy_request_to_queue.py
> +            mock_get_dbconnect_info: MagicMock,
2 mislabeled mocks. Make the same changes here as in happy-path.

2021-07-14 13:47 UTC, rizbi-hassan approved these changes

2021-07-14 15:50 UTC, bhazuka commented
Closed and reopening because of issues with Snyk

2021-07-14 15:50 UTC, closed without merging