Centralized requirements
nasa/cumulus-orca pull request #130
Opened 2021-08-12 20:58 UTC by AndrewDorn

## Summary of Changes

Please write a sentence or two summarizing the proposed change.

Addresses [ORCA-238: Move all terraform requirements to a single versions.tf file for deployments](https://bugs.earthdata.nasa.gov/browse/ORCA-238)

## Changes

* Centralized requirements to single file.

## How Has This Been Tested?

Deployed to AWS.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] Unit tests
    - [ ] Integration tests
    - [ ] Manual tests (outlined above)
- [x] New and existing unit tests pass locally with my changes
    - [x] Automated tests passing (if not fork)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code has passed security scanning
    - [x] Snyk
    - [x] git-secrets

2021-08-12 21:34 UTC, bhazuka requested changes
Couple of minor items to adjust. Otherwise looks good, just need to resolve the merge issues.

2021-08-12 21:34 UTC, bhazuka commented on versions.tf
> +terraform {
I wonder if we shouldn't add a required version for terraform as well ">=0.13.6" per Abdelhaks example 
```
terraform {
  required_version = ">= 0.13.6"
  required_providers {
    aws        = ">= 3.40.0"
    local      = ">= 1.4"
    kubernetes = ">= 1.11.1"
    http = {
      source  = "terraform-aws-modules/http"
      version = ">= 2.4.1"
    }
  }
}
```

2021-08-12 21:34 UTC, bhazuka commented on versions.tf
> +      version = ">= 3.5.0"
Looked at versions for Cumulus, wondering if we shouldn't bump the minimum version to match up to 3.14.1

2021-08-12 21:45 UTC, rizbi-hassan approved these changes

2021-08-13 13:05 UTC, bhazuka approved these changes

2021-08-13 13:31 UTC, merged