Feature/orca 301 Create input/output/config schema for get_current_archive_list
nasa/cumulus-orca pull request #232
Opened 2022-01-27 16:05 UTC by AndrewDorn

## Summary of Changes

Please write a sentence or two summarizing the proposed change.

Addresses [ORCA-301: Create input/output/config schema for get_current_archive_list](https://bugs.earthdata.nasa.gov/browse/ORCA-301)

## Changes

* Added schemas for get_current_archive_list
* Added basic files for lambda

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

It has not.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
    - [x] Automated tests passing (if not fork)
    - [x] Manual testing/integration testing passes (if forked)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code has passed security scanning
    - [x] Snyk
    - [x] git-secrets

2022-01-27 20:38 UTC, rizbih approved these changes
FYI output of this lambda will be input of perform_orca_reconcile lambda which is the 2nd step of the step function workflow.

2022-01-27 23:45 UTC, bhazuka requested changes
You may want to copy over and modify the api creation script from https://github.com/nasa/cumulus-orca/blob/master/shared_libraries/bin/build_api.sh

2022-01-27 23:45 UTC, bhazuka commented on tasks/get_current_archive_list/bin/run_tests.sh
> +
May want to add additional tests like linting, code smell, formatting, etc. like we have in https://github.com/nasa/cumulus-orca/blob/master/shared_libraries/bin/run_tests.sh

2022-01-28 14:57 UTC, bhazuka approved these changes
Looks good

2022-01-28 15:13 UTC, merged