docs: Standardized scripts in request_files Update request_files script and README to match the standard like in other lambdas and create build_api.sh
nasa/cumulus-orca pull request #284
Opened 2022-05-26 15:29 UTC by AndrewDorn

## Summary of Changes

Update request_files script and README to match the standard like in other lambdas and create build_api.sh

Addresses [ORCA-434: Update request_files script and README to match the standard like in other lambdas and create build_api.sh](https://bugs.earthdata.nasa.gov/browse/ORCA-434)

## Changes

* Updated scripts
* Generated API
* Added `nosec` to some randomized test values

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

Scripts run locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [x] User documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
    - [x] Unit tests
- [x] New and existing unit tests pass locally with my changes
    - [x] Automated tests passing (if not fork)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code has passed security scanning
    - [x] Snyk
    - [x] git-secrets

2022-05-31 13:44 UTC, bhazuka requested changes
Overall looks good to me. I would do 1 minor addition to README. See my note.

2022-05-31 13:44 UTC, bhazuka commented on tasks/request_files/README.md
>  ```
May want to add a sentence and link to the schemas like we do in the other Lambdas

2022-05-31 13:44 UTC, rizbihassan requested changes
Looks good overall. 
Should we add input/output schema examples like in https://github.com/nasa/cumulus-orca/tree/develop/tasks/request_status_for_granule#inputoutput-schemas-and-examples?

2022-05-31 18:55 UTC, AndrewDorn commented
> Looks good overall. Should we add input/output schema examples like in https://github.com/nasa/cumulus-orca/tree/develop/tasks/request_status_for_granule#inputoutput-schemas-and-examples?

Added

2022-05-31 18:57 UTC, rizbihassan approved these changes

2022-06-01 14:57 UTC, bhazuka approved these changes
Looks good to me.

2022-06-02 14:00 UTC, merged