Feature/orca 465
nasa/cumulus-orca pull request #293
Opened 2022-06-17 14:03 UTC by rizbihassan

## Summary of Changes

Addresses [ORCA-465: Create or modify deployment script to automate ORCA buckets and dynamodb table creation for running the bamboo.](https://bugs.earthdata.nasa.gov/browse/ORCA-465)

## Changes

* updated bin/deployment-rds.sh to include s3 buckets and dynamo deployment

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

ran the script in bamboo when 
- there were no resources present https://ci.earthdata.nasa.gov/browse/ORCA-PN-DRC-52/log
- when the resources were already present. https://ci.earthdata.nasa.gov/browse/ORCA-PN-DRC-56/log
- when some resources were modified https://ci.earthdata.nasa.gov/browse/ORCA-PN-DRC-55/log

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

2022-06-17 14:46 UTC, AndrewDorn approved these changes
I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.

I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.

2022-06-17 15:10 UTC, rizbihassan commented
> I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> 
> I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.

We can actually create the buckets in any account from the bamboo pipeline.

When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.

2022-06-17 15:46 UTC, AndrewDorn commented
> > I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> > I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.
> 
> We can actually create the buckets in any account from the bamboo pipeline.
> 
> When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.

Doesn't that move everything though? For a realistic test environment, the Orca buckets should be in a separate account from stuff like our lambdas.

2022-06-17 16:05 UTC, rizbihassan commented
> > > I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> > > I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.
> > 
> > 
> > We can actually create the buckets in any account from the bamboo pipeline.
> > When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.
> 
> Doesn't that move everything though? For a realistic test environment, the Orca buckets should be in a separate account from stuff like our lambdas.

hmm true it moves everything to a new account.

Do you know if we want to deploy all the buckets to a separate account or only prefix-orca-primary?

2022-06-17 17:02 UTC, AndrewDorn commented
> > > > I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> > > > I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.
> > > 
> > > 
> > > We can actually create the buckets in any account from the bamboo pipeline.
> > > When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.
> > 
> > 
> > Doesn't that move everything though? For a realistic test environment, the Orca buckets should be in a separate account from stuff like our lambdas.
> 
> hmm true it moves everything to a new account.
> 
> Do you know if we want to deploy all the buckets to a separate account or only prefix-orca-primary?

Also the reports bucket. Then they'll need proper permissions for cross-account access. I'm guessing we're getting away with no permissions because they're in the same account.

2022-06-17 17:24 UTC, rizbihassan commented
> > > > > I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> > > > > I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.
> > > > 
> > > > 
> > > > We can actually create the buckets in any account from the bamboo pipeline.
> > > > When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.
> > > 
> > > 
> > > Doesn't that move everything though? For a realistic test environment, the Orca buckets should be in a separate account from stuff like our lambdas.
> > 
> > 
> > hmm true it moves everything to a new account.
> > Do you know if we want to deploy all the buckets to a separate account or only prefix-orca-primary?
> 
> Also the reports bucket. Then they'll need proper permissions for cross-account access. I'm guessing we're getting away with no permissions because they're in the same account.

added orca_reports bucket. This was added in the unreleased version that's why forgot to add this.

If we are only planning to deploy prefix-orca-primary to DR account and other buckets in sandbox, then we have to create a new stage in bamboo to deploy that bucket only using that account's aws access keys. Then when we run the deployment pipeline in sandbox account, we will use the aws access keys for that sandbox account. That's what I can think of right now otherwise we have to manually create the bucket and add cross account policy in DR account for now using cli.

2022-06-17 19:02 UTC, rizbihassan commented
> > > > > > > I like including this in the TF to automatically tie into the `terraform destroy`, especially since that's how we want to eventually create these buckets anyway.
> > > > > > > I do think we should put a card on the backlog to have the Orca buckets created in a different account. I understand that's outside the scope of initial implementation.
> > > > > > 
> > > > > > 
> > > > > > We can actually create the buckets in any account from the bamboo pipeline.
> > > > > > When you run the pipeline, you add the aws_access_key and secret_access_key which tells bamboo which aws account to deploy the buckets to.
> > > > > 
> > > > > 
> > > > > Doesn't that move everything though? For a realistic test environment, the Orca buckets should be in a separate account from stuff like our lambdas.
> > > > 
> > > > 
> > > > hmm true it moves everything to a new account.
> > > > Do you know if we want to deploy all the buckets to a separate account or only prefix-orca-primary?
> > > 
> > > 
> > > Also the reports bucket. Then they'll need proper permissions for cross-account access. I'm guessing we're getting away with no permissions because they're in the same account.
> > 
> > 
> > added orca_reports bucket. This was added in the unreleased version that's why forgot to add this.
> > If we are only planning to deploy prefix-orca-primary to DR account and other buckets in sandbox, then we have to create a new stage in bamboo to deploy that bucket only using that account's aws access keys. Then when we run the deployment pipeline in sandbox account, we will use the aws access keys for that sandbox account. That's what I can think of right now otherwise we have to manually create the bucket and add cross account policy in DR account for now using cli.
> 
> We'd also have prefix-orca-reports in the DR account, but otherwise sounds right. That's why I think it should be a backlog card.

yup just making sure. 

created https://bugs.earthdata.nasa.gov/browse/ORCA-476

2022-06-20 15:01 UTC, bhazuka requested changes
Overall it is looking good but, some items we should talk through as a team.

2022-06-20 18:17 UTC, rizbihassan commented on bin/deployment-rds.sh
> +resource "aws_s3_bucket" "level0" {
Do we have an existing glacier bucket where objects will be moved from this level0 bucket?
or do we have to create a new bucket for this?

2022-06-20 18:17 UTC, rizbihassan commented on bin/deployment-rds.sh
> +# create buckets
added tags to the buckets.

I was initially thinking to use aws cli in the delete script to delete objects and then delete the buckets while doing the destroy but I guess adding `force_destroy = true` makes sense here. Added.

2022-06-20 18:18 UTC, rizbihassan commented on bin/deployment-rds.sh
> +resource "aws_s3_bucket" "orca-reports" {
yes we can add a rule to delete after 30 days. Will note it in ORCA-476

2022-06-20 18:31 UTC, rizbihassan commented on bin/deployment-rds.sh
> +cat << EOF > resources.tf.template
yes that could be another option. Put this under something like `deployment_templates/` in our repo

2022-06-20 18:32 UTC, rizbihassan commented on website/docs/developer/development-guide/code/versioning-releases.md
> -Make sure the proper buckets, dynamoDB table and the EC2 key pair are first created manually using the same prefix before running the pipeline. See this cumulus [documentation](https://nasa.github.io
yes it won't hurt to keep them. Added back.

2022-06-20 19:44 UTC, rizbihassan commented on bin/deployment-rds.sh
> +  -lock=false \
oops removed. Added that while testing

2022-06-21 13:10 UTC, rizbihassan commented on bin/deployment-rds.sh
> +resource "aws_s3_bucket" "level0" {
add a lifecycle config similar to glacier bucket in cumulus OU account.

2022-06-21 13:14 UTC, rizbihassan commented on bin/deployment-rds.sh
> +resource "aws_s3_bucket" "orca-primary" {
deploy WORM bucket in DR account

2022-06-22 13:39 UTC, rizbihassan commented on integration_test/deployment-rds.sh
> +git clone --branch develop --single-branch https://github.com/nasa/cumulus-orca.git && cd integration_test
bamboo throws an error without cloning the repo.
the `rds-deployment.sh` did not clone the repo before but we need this now to use the integration_test/buckets.tf.template

2022-06-28 16:32 UTC, AndrewDorn approved these changes

2022-06-28 18:57 UTC, bhazuka approved these changes

2022-06-28 18:58 UTC, merged