Feature/orca 461 DB Connection Info Validation
nasa/cumulus-orca pull request #344
Opened 2022-10-17 18:47 UTC by AndrewDorn

## Summary of Changes

Added consistent validation of database connection parameters that may be used in SQL construction.

Addresses [ORCA-461: Update parameterization in db_deploy sql](https://bugs.earthdata.nasa.gov/browse/ORCA-461)

## Changes

* Switched db_deploy to updated shared_db code
* Added validation to several db parameters

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Testing in-progress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [ ] CHANGELOG.md
    - [ ] Testing documentation
    - [ ] Development documentation
    - [ ] User documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
    - [x] Unit tests
    - [ ] Integration tests
- [ ] New and existing unit tests pass locally with my changes
    - [ ] Automated tests passing (if not fork)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code has passed security scanning
    - [x] Snyk
    - [x] git-secrets

2022-10-19 16:16 UTC, rizbihassan approved these changes
looks good to me

2022-10-20 14:40 UTC, bhazuka requested changes
Overall looks good to me, A couple of minor items to look at an comment on.

2022-10-20 16:21 UTC, AndrewDorn commented on shared_libraries/orca_shared/database/use_cases/validation.py
> +    if password is None or len(password) < 12:
https://bugs.earthdata.nasa.gov/browse/ORCA-573

2022-10-20 16:21 UTC, AndrewDorn commented on shared_libraries/orca_shared/database/use_cases/validation.py
> +    Validates the given name against documented Postgres restrictions.
Added some newly supported characters. https://bugs.earthdata.nasa.gov/browse/ORCA-572 for remainder.

2022-10-20 20:44 UTC, merged