Feature/orca 614 Migrate internal reconciliation db code to graphql
nasa/cumulus-orca pull request #393
Opened 2023-03-08 20:19 UTC by AndrewDorn

## Summary of Changes

Please write a sentence or two summarizing the proposed change.

Addresses [ORCA-614: Migrate internal reconciliation db code to graphql](https://bugs.earthdata.nasa.gov/browse/ORCA-614)

## Changes

* Detailed list or prose of changes
* ...

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests (unit, integration, ad-hoc, or otherwise) that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [ ] CHANGELOG.md
    - [ ] Testing documentation
    - [ ] Development documentation
    - [ ] User documentation
    - [ ] (Additional here)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] Unit tests
    - [ ] Integration tests
    - [ ] Manual tests (outlined above)
- [ ] New and existing unit tests pass locally with my changes
    - [ ] Automated tests passing (if not fork)
    - [ ] Manual testing/integration testing passes (if forked)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code has passed security scanning
    - [ ] Snyk
    - [ ] git-secrets

2023-03-10 20:18 UTC, rizbihassan reviewed
Lots of stuff and migration. Looks good to me from what I understand about graphql.
What happens to the api gateway for internal reconciliation now? In other words, does anything change on how we access the api?

2023-03-10 20:20 UTC, AndrewDorn commented on modules/orca/main.tf
> +  s3_access_credentials_secret_arn = module.orca_secretsmanager.s3_access_credentials_secret_arn
Same key. No migration needed.

2023-03-10 20:21 UTC, AndrewDorn commented
> Lots of stuff and migration. Looks good to me from what I understand about graphql. What happens to the api gateway for internal reconciliation now? In other words, does anything change on how we access the api?

Not from this. These endpoints are internal, and are not exposed via API Gateway.

2023-03-13 18:20 UTC, rizbihassan requested changes
might want to update changelog.md as well

2023-03-14 13:06 UTC, rizbihassan approved these changes
looks good. Once this is merged, I will pull in the changes and fix the conflicts.

2023-03-14 14:11 UTC, merged