Feature/orca 678 db_deploy: Add collection_id for recovery jobs
nasa/cumulus-orca pull request #414
Opened 2023-05-11 16:17 UTC by AndrewDorn

## Summary of Changes

Added collection_id to recovery status tables.

Addresses [ORCA-678: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/ORCA-678)

## Changes

* Added collection_id column to recovery_files and recovery_jobs
* Added migration to add column and populate with data from `granules` table
* Added tests

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Code run against AWS deployment.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [x] CHANGELOG.md
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
    - [x] Unit tests
- [x] New and existing unit tests pass locally with my changes
    - [x] Automated tests passing (if not fork)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My code has passed security scanning
    - [x] Snyk
    - [x] git-secrets

2023-05-11 16:19 UTC, AndrewDorn commented on CHANGELOG.md
> +- *ORCA-679* Updated area in recovery where granule ID was treated as a globally unique key. Per Cumulus updates, uniqueness is no granule ID plus collection ID.
This is the Epic number. Opted to create a side-branch and merge into that to keep develop functional.

2023-05-11 18:45 UTC, rizbihassan requested changes

2023-05-11 19:10 UTC, AndrewDorn commented on CHANGELOG.md
> +- *ORCA-679* Updated area in recovery where granule ID was treated as a globally unique key. Per Cumulus updates, uniqueness is no granule ID plus collection ID.
Fixed

2023-05-11 19:10 UTC, AndrewDorn commented on tasks/db_deploy/migrations/migrate_versions_6_to_7/migrate.py
> +Description: Migrates the ORCA schema from version 5 to version 6.
Fixed

2023-05-11 19:10 UTC, AndrewDorn commented on tasks/db_deploy/migrations/migrate_versions_6_to_7/migrate_sql.py
> +Description: All the SQL used for creating and migrating the ORCA schema to version 6.
Fixed

2023-05-11 19:11 UTC, AndrewDorn commented on tasks/db_deploy/test/unit_tests/migrations/migrate_versions_6_to_7/test_migrate_sql_v7.py
> +Name: test_migrate_sql_v6.py
Fixed

2023-05-12 13:29 UTC, rizbihassan approved these changes

2023-05-12 13:33 UTC, merged