feature/ORCA-731 - Investigate and fix warnings from unit tests in the shared_libraries
nasa/cumulus-orca pull request #461
Opened 2023-11-01 20:47 UTC by zroehrich

## Summary of Changes

Addresses [ORCA-731: Investigate and fix warnings from unit tests in the shared_libraries.](https://bugs.earthdata.nasa.gov/browse/ORCA-731)

## Changes

* Updating boto3 to resolve warnings in unit tests, passes with no warnings using Python 3.9 and Python 3.10

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually tested using the run_tests.sh script.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
    - [x] Manual tests (outlined above)
- [x] My code has passed security scanning
    - [x] git-secrets
    - [x] Snyk

2023-11-02 13:04 UTC, bhazuka approved these changes
Looks good to me

2023-11-02 17:17 UTC, rizbihassan requested changes
Still getting these warning messages while running bin/run_tests.sh using python 3.9. Do you see these warnings when you run bin/run_tests.sh from cumulus-orca directory?

```
orca_shared/recovery/test/unit_tests/test_shared_recovery.py .....                                                                                                                        [100%]

======================================================================================= warnings summary ========================================================================================
orca_shared/database/test/unit_tests/test_shared_db.py: 2457 warnings
orca_shared/database/test/unit_tests/adapters/api/test_aws.py: 819 warnings
orca_shared/recovery/test/unit_tests/test_shared_recovery.py: 2485 warnings
  /Users/rhassan/cumulus-orca/shared_libraries/venv/lib/python3.9/site-packages/responses/__init__.py:622: DeprecationWarning: stream argument is deprecated. Use stream parameter in request directly
    warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================== 38 passed, **5761 warnings** in 15.90s ===============================================================================
INFO: Running 'deactivate' ...
INFO: Cleaning up virtual environment ...
INFO: Running 'rm -rf venv' ...
All done! ✨ 🍰 ✨
3 files left unchanged.
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.9.13
[node_visitor]  WARNING Unable to find qualified name for module: delete_old_reconcile_jobs.py

Running tests in tasks/extract_filepaths_for_granule

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 14:22:02.673845

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 745
        Total lines skipped (#nosec): 0
        Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
        Total issues (by confidence):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
Files skipped (0):
INFO: Running unit and coverage tests ...
============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/rhassan/cumulus-orca/tasks/extract_filepaths_for_granule
collected 12 items

test/unit_tests/test_extract_file_paths_for_granule.py ............      [100%]

============================== 12 passed in 0.41s ==============================
Name                               Stmts   Miss  Cover
------------------------------------------------------
extract_filepaths_for_granule.py     135     13    90%
------------------------------------------------------
TOTAL                                135     13    90%
INFO: Running 'deactivate' ...
INFO: Cleaning up virtual environment ...
INFO: Running 'rm -rf venv' ...
All done! ✨ 🍰 ✨
4 files left unchanged.
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.9.13
[node_visitor]  WARNING Unable to find qualified name for module: extract_filepaths_for_granule.py

Running tests in tasks/get_current_archive_list

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 14:23:15.425463

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 1586
        Total lines skipped (#nosec): 4
        Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
        Total issues (by confidence):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
Files skipped (0):
INFO: Running unit and coverage tests ...
============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/rhassan/cumulus-orca/tasks/get_current_archive_list
collected 22 items

test/unit_tests/test_get_current_archive_list.py ......................  [100%]

============================== 22 passed in 2.23s ==============================
Name                          Stmts   Miss  Cover
-------------------------------------------------
get_current_archive_list.py     172      6    97%
-------------------------------------------------
TOTAL                           172      6    97%
INFO: Running 'deactivate' ...
INFO: Cleaning up virtual environment ...
INFO: Running 'rm -rf venv' ...
All done! ✨ 🍰 ✨
3 files left unchanged.
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.9.13
[node_visitor]  WARNING Unable to find qualified name for module: get_current_archive_list.py

Running tests in tasks/internal_reconcile_report_job

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 14:24:30.393098

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 599
        Total lines skipped (#nosec): 22
        Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
        Total issues (by confidence):
                Undefined: 0
                Low: 0
                Medium: 0
                High: 0
Files skipped (0):
INFO: Running unit and coverage tests ...
============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/rhassan/cumulus-orca/tasks/internal_reconcile_report_job
collected 10 items

test/unit_tests/test_internal_reconcile_report_job.py ..........         [100%]

============================== 10 passed in 2.16s ==============================
Name                               Stmts   Miss  Cover
------------------------------------------------------
internal_reconcile_report_job.py      75      3    96 [...]

2023-11-02 19:16 UTC, zroehrich commented
> Still getting these warning messages while running bin/run_tests.sh using python 3.9. Do you see these warnings when you run bin/run_tests.sh from cumulus-orca directory?

I do not see those using Python 3.9. I do now see a warning with collections but I don't see anywhere where we are using that library.
`
Running tests in shared_libraries

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 18:33:14.718823

Test results:
	No issues identified.

Code scanned:
	Total lines of code: 1789
	Total lines skipped (#nosec): 18
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 0
		Medium: 0
		High: 0
	Total issues (by confidence):
		Undefined: 0
		Low: 0
		Medium: 0
		High: 0
Files skipped (0):
INFO: Running unit and coverage tests ...
============================= test session starts ==============================
platform darwin -- Python 3.9.18, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/zroehrich/Documents/ORCA/713/cumulus-orca/shared_libraries
collected 38 items

orca_shared/database/test/unit_tests/test_shared_db.py .........         [ 23%]
orca_shared/database/test/unit_tests/adapters/api/test_aws.py ...        [ 31%]
orca_shared/database/test/unit_tests/use_cases/test_create_postgres_connection_uri.py . [ 34%]
...                                                                      [ 42%]
orca_shared/database/test/unit_tests/use_cases/test_validation.py ...... [ 57%]
.....                                                                    [ 71%]
orca_shared/reconciliation/test/unit_tests/test_shared_reconciliation.py . [ 73%]
.....                                                                    [ 86%]
orca_shared/recovery/test/unit_tests/test_shared_recovery.py .....       [100%]

============================== 38 passed in 6.93s ==============================
Name                                                                                    Stmts   Miss  Cover
-----------------------------------------------------------------------------------------------------------
orca_shared/__init__.py                                                                    13      2    85%
orca_shared/database/__init__.py                                                            1      0   100%
orca_shared/database/adapters/__init__.py                                                   0      0   100%
orca_shared/database/adapters/api/__init__.py                                               1      0   100%
orca_shared/database/adapters/api/aws.py                                                   25      0   100%
orca_shared/database/entities/__init__.py                                                   1      0   100%
orca_shared/database/entities/postgres_connection_info.py                                  11      0   100%
orca_shared/database/shared_db.py                                                          70      0   100%
orca_shared/database/test/unit_tests/adapters/__init__.py                                   0      0   100%
orca_shared/database/test/unit_tests/adapters/api/__init__.py                               0      0   100%
orca_shared/database/test/unit_tests/adapters/api/test_aws.py                              37      0   100%
orca_shared/database/test/unit_tests/test_shared_db.py                                     98      2    98%
orca_shared/database/test/unit_tests/use_cases/__init__.py                                  0      0   100%
orca_shared/database/test/unit_tests/use_cases/test_create_postgres_connection_uri.py      50      0   100%
orca_shared/database/test/unit_tests/use_cases/test_validation.py                          96      0   100%
orca_shared/database/use_cases/__init__.py                                                  1      0   100%
orca_shared/database/use_cases/create_postgres_connection_uri.py                           17      0   100%
orca_shared/database/use_cases/validation.py                                               44      0   100%
orca_shared/reconciliation/__init__.py                                                      1      0   100%
orca_shared/reconciliation/shared_reconciliation.py                                        39      0   100%
orca_shared/reconciliation/test/unit_tests/test_shared_reconciliation.py                   90      2    98%
orca_shared/recovery/__init__.py                                                            1      0   100%
orca_shared/recovery/shared_recovery.py                                                    88      7    92%
orca_shared/recovery/test/unit_tests/test_shared_recovery.py                               87      0   100%
-----------------------------------------------------------------------------------------------------------
TOTAL                                                                                     771     13    98%
INFO: Running 'deactivate' ...
INFO: Cleaning up virtual environment ...
INFO: Running 'rm -rf venv' ...
/Users/zroehrich/Documents/ORCA/713/cumulus-orca
Running unit tests in parallel...

Running tests in tasks/copy_from_archive

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 18:34:30.223915

Test results:
	No issues identified.

Code scanned:
	Total lines of code: 733
	Total lines skipped (#nosec): 9
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 0
		Medium: 0
		High: 0
	Total issues (by confidence):
		Undefined: 0
		Low: 0
		Medium: 0
		High: 0
Files skipped (0):
INFO: Running unit and coverage tests ...
============================= test session starts ==============================
platform darwin -- Python 3.9.18, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/zroehrich/Documents/ORCA/713/cumulus-orca/tasks/copy_from_archive
collected 7 items

test/unit_tests/test_copy_from_archive.py .......                        [100%]

============================== 7 passed in 1.11s ===============================
Name                   Stmts   Miss  Cover
------------------------------------------
copy_from_archive.py     121     16    87%
------------------------------------------
TOTAL                    121     16    87%
INFO: Running 'deactivate' ...
INFO: Cleaning up virtual environment ...
INFO: Running 'rm -rf venv' ...

Running tests in tasks/copy_to_archive

INFO: Running 'create_and_activate_venv' ...
INFO: Creating virtual environment ...
INFO: Running 'python3 -m venv venv' ...
INFO: Running 'source venv/bin/activate' ...
INFO: Virtual environment ready.
INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ...
INFO: Checking formatting and style of code ...
INFO: Sorting imports ...
INFO: Formatting with black ...
INFO: Checking lint rules ...
INFO: Running code smell security tests ...
Run started:2023-11-02 18:35:36.393981

Test results:
	No issues identified.

Code scanned:
	Total lines of code: 1420
	Total lines skipped (#nosec): 5
	Tota [...]

2023-11-02 19:28 UTC, rizbihassan commented on shared_libraries/requirements.txt
> +boto3~=1.28.76
Also update CHANGELOG.md to add this update.

2023-11-02 19:29 UTC, rizbihassan commented
Also need to update CHANGELOG.md to add this under Unreleased section.

2023-11-02 19:32 UTC, rizbihassan commented
> > Still getting these warning messages while running bin/run_tests.sh using python 3.9. Do you see these warnings when you run bin/run_tests.sh from cumulus-orca directory?
> 
> I do not see those using Python 3.9. I do now see a warning with collections but I don't see anywhere where we are using that library. ` Running tests in shared_libraries
> 
> INFO: Running 'create_and_activate_venv' ... INFO: Creating virtual environment ... INFO: Running 'python3 -m venv venv' ... INFO: Running 'source venv/bin/activate' ... INFO: Virtual environment ready. INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ... INFO: Checking formatting and style of code ... INFO: Sorting imports ... INFO: Formatting with black ... INFO: Checking lint rules ... INFO: Running code smell security tests ... Run started:2023-11-02 18:33:14.718823
> 
> Test results: No issues identified.
> 
> Code scanned: Total lines of code: 1789 Total lines skipped (#nosec): 18 Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0
> 
> Run metrics: Total issues (by severity): Undefined: 0 Low: 0 Medium: 0 High: 0 Total issues (by confidence): Undefined: 0 Low: 0 Medium: 0 High: 0 Files skipped (0): INFO: Running unit and coverage tests ... ============================= test session starts ============================== platform darwin -- Python 3.9.18, pytest-7.4.0, pluggy-1.3.0 rootdir: /Users/zroehrich/Documents/ORCA/713/cumulus-orca/shared_libraries collected 38 items
> 
> orca_shared/database/test/unit_tests/test_shared_db.py ......... [ 23%] orca_shared/database/test/unit_tests/adapters/api/test_aws.py ... [ 31%] orca_shared/database/test/unit_tests/use_cases/test_create_postgres_connection_uri.py . [ 34%] ... [ 42%] orca_shared/database/test/unit_tests/use_cases/test_validation.py ...... [ 57%] ..... [ 71%] orca_shared/reconciliation/test/unit_tests/test_shared_reconciliation.py . [ 73%] ..... [ 86%] orca_shared/recovery/test/unit_tests/test_shared_recovery.py ..... [100%]
> 
> ## ============================== 38 passed in 6.93s ==============================
> Name Stmts Miss Cover
> ## orca_shared/**init**.py 13 2 85%
> orca_shared/database/**init**.py 1 0 100%
> orca_shared/database/adapters/**init**.py 0 0 100%
> orca_shared/database/adapters/api/**init**.py 1 0 100%
> orca_shared/database/adapters/api/aws.py 25 0 100%
> orca_shared/database/entities/**init**.py 1 0 100%
> orca_shared/database/entities/postgres_connection_info.py 11 0 100%
> orca_shared/database/shared_db.py 70 0 100%
> orca_shared/database/test/unit_tests/adapters/**init**.py 0 0 100%
> orca_shared/database/test/unit_tests/adapters/api/**init**.py 0 0 100%
> orca_shared/database/test/unit_tests/adapters/api/test_aws.py 37 0 100%
> orca_shared/database/test/unit_tests/test_shared_db.py 98 2 98%
> orca_shared/database/test/unit_tests/use_cases/**init**.py 0 0 100%
> orca_shared/database/test/unit_tests/use_cases/test_create_postgres_connection_uri.py 50 0 100%
> orca_shared/database/test/unit_tests/use_cases/test_validation.py 96 0 100%
> orca_shared/database/use_cases/**init**.py 1 0 100%
> orca_shared/database/use_cases/create_postgres_connection_uri.py 17 0 100%
> orca_shared/database/use_cases/validation.py 44 0 100%
> orca_shared/reconciliation/**init**.py 1 0 100%
> orca_shared/reconciliation/shared_reconciliation.py 39 0 100%
> orca_shared/reconciliation/test/unit_tests/test_shared_reconciliation.py 90 2 98%
> orca_shared/recovery/**init**.py 1 0 100%
> orca_shared/recovery/shared_recovery.py 88 7 92%
> orca_shared/recovery/test/unit_tests/test_shared_recovery.py 87 0 100%
> TOTAL 771 13 98% INFO: Running 'deactivate' ... INFO: Cleaning up virtual environment ... INFO: Running 'rm -rf venv' ... /Users/zroehrich/Documents/ORCA/713/cumulus-orca Running unit tests in parallel...
> 
> Running tests in tasks/copy_from_archive
> 
> INFO: Running 'create_and_activate_venv' ... INFO: Creating virtual environment ... INFO: Running 'python3 -m venv venv' ... INFO: Running 'source venv/bin/activate' ... INFO: Virtual environment ready. INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ... INFO: Checking formatting and style of code ... INFO: Sorting imports ... INFO: Formatting with black ... INFO: Checking lint rules ... INFO: Running code smell security tests ... Run started:2023-11-02 18:34:30.223915
> 
> Test results: No issues identified.
> 
> Code scanned: Total lines of code: 733 Total lines skipped (#nosec): 9 Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0
> 
> Run metrics: Total issues (by severity): Undefined: 0 Low: 0 Medium: 0 High: 0 Total issues (by confidence): Undefined: 0 Low: 0 Medium: 0 High: 0 Files skipped (0): INFO: Running unit and coverage tests ... ============================= test session starts ============================== platform darwin -- Python 3.9.18, pytest-7.4.0, pluggy-1.3.0 rootdir: /Users/zroehrich/Documents/ORCA/713/cumulus-orca/tasks/copy_from_archive collected 7 items
> 
> test/unit_tests/test_copy_from_archive.py ....... [100%]
> 
> ## ============================== 7 passed in 1.11s ===============================
> Name Stmts Miss Cover
> ## copy_from_archive.py 121 16 87%
> TOTAL 121 16 87% INFO: Running 'deactivate' ... INFO: Cleaning up virtual environment ... INFO: Running 'rm -rf venv' ...
> 
> Running tests in tasks/copy_to_archive
> 
> INFO: Running 'create_and_activate_venv' ... INFO: Creating virtual environment ... INFO: Running 'python3 -m venv venv' ... INFO: Running 'source venv/bin/activate' ... INFO: Virtual environment ready. INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ... INFO: Checking formatting and style of code ... INFO: Sorting imports ... INFO: Formatting with black ... INFO: Checking lint rules ... INFO: Running code smell security tests ... Run started:2023-11-02 18:35:36.393981
> 
> Test results: No issues identified.
> 
> Code scanned: Total lines of code: 1420 Total lines skipped (#nosec): 5 Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0
> 
> Run metrics: Total issues (by severity): Undefined: 0 Low: 0 Medium: 0 High: 0 Total issues (by confidence): Undefined: 0 Low: 0 Medium: 0 High: 0 Files skipped (0): INFO: Running unit and coverage tests ... ============================= test session starts ============================== platform darwin -- Python 3.9.18, pytest-7.4.0, pluggy-1.3.0 rootdir: /Users/zroehrich/Documents/ORCA/713/cumulus-orca/tasks/copy_to_archive collected 18 items
> 
> test/unit_tests/test_copy_to_archive.py .................. [100%]
> 
> ## ============================== 18 passed in 5.16s ==============================
> Name Stmts Miss Cover
> ## copy_to_archive.py 195 22 89%
> TOTAL 195 22 89% INFO: Running 'deactivate' ... INFO: Cleaning up virtual environment ... INFO: Running 'rm -rf venv' ...
> 
> Running tests in tasks/copy_to_archive_adapter
> 
> INFO: Running 'create_and_activate_venv' ... INFO: Creating virtual environment ... INFO: Running 'python3 -m venv venv' ... INFO: Running 'source venv/bin/activate' ... INFO: Virtual environment ready. INFO: Running 'pip install -q --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org' ... INFO: Checking formatting and style of code ... INFO: Sorting imports ... INFO: Formatting with black ... INFO: Checking lint rules ... INFO: Running code smell security tests ... Run started:2023-11-02 18:36:46.772304
> 
> Test results: No issues identified.
> 
> Code scanned: Total lines of code: 375 Total lines skipped (#nosec): 4 Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0
> 
> Run metrics: Total issues (by severity): Undefined: 0 Low: 0 Medium: 0 High: 0 Total issues (by confidence): Undefined: 0 Low: 0 Medium: 0 High: 0 Files [...]

2023-11-02 20:50 UTC, zroehrich commented
Just ran it in bamboo and I'm not seeing the same results that you are

https://ci.earthdata.nasa.gov/download/ORCA-OI392-JOB1/build_logs/ORCA-OI392-JOB1-2.log

2023-11-03 12:39 UTC, rizbihassan commented on CHANGELOG.md
> +- *ORCA-731* Updated boto3 library used for unit tests to version 1.28.76 from version 1.18.40.
Maybe also add that this was done to fix the unit tests warning messages.

2023-11-03 12:54 UTC, rizbihassan commented
> Just ran it in bamboo and I'm not seeing the same results that you are
> 
> https://ci.earthdata.nasa.gov/download/ORCA-OI392-JOB1/build_logs/ORCA-OI392-JOB1-2.log

Interesting! Not sure why I am seeing those warnings when I run those. Maybe something to do with my env setup.

2023-11-03 13:26 UTC, rizbihassan approved these changes

2023-11-03 14:03 UTC, merged