Feature/orca 139
nasa/cumulus-orca pull request #56
Opened 2021-02-23 21:41 UTC by Quarriers89

## Summary of Changes

Added NGAP and OU to the ORCA Glossary.

Addresses [ORCA-139: As an engineer, I need to add NGAP and OU to ORCA glossary.](https://bugs.earthdata.nasa.gov/browse/ORCA-139)

## Changes

* Added NGAP and OU to glossary
* ...

## Type of change

Please delete options that are not relevant.

- [X] This change requires a documentation update

## How Has This Been Tested?

N/A

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [X] User documentation
  - [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
    - [ ] Unit tests
    - [ ] Integration tests
    - [ ] Manual tests (outlined above)
- [ ] New and existing unit tests pass locally with my changes
    - [ ] Automated tests passing (if not fork)
    - [ ] Manual testing/integration testing passes (if forked)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code has passed security scanning
    - [ ] Snyk
    - [ ] git-secrets

## What is the current behavior?

N/A

## What is the expected correct/added behavior?

N/A

## Relevant logs and/or screenshots

N/A

## Possible fixes

N/A

2021-02-24 16:02 UTC, bhazuka requested changes
Minor item to check on.

2021-02-24 16:02 UTC, bhazuka commented on README.md
> +PostToCMR's "Next" parameter equal to "CopyToGlacier".
Remove `PostToCMR's`

2021-02-26 16:34 UTC, Quarriers89 commented on README.md
> +PostToCMR's "Next" parameter equal to "CopyToGlacier".
Removed PostToCMR's.

2021-02-26 16:45 UTC, bhazuka approved these changes

2021-02-26 16:45 UTC, merged